import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

export type Language = 'id' | 'en';

interface LanguageState {
  lang: Language;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      lang: 'id',
      setLang: (lang) => set({ lang }),
      toggleLang: () => set({ lang: get().lang === 'id' ? 'en' : 'id' }),
    }),
    {
      name: 'jadwale-language-storage',
      storage: createJSONStorage(() => localStorage),
    }
  )
);

export const TRANSLATIONS = {
  id: {
    appName: 'Jadwale',
    appSubtitle: 'Penjadwalan Otomatis',
    home: 'Beranda',
    dashboard: 'Dashboard',
    jadwal: 'Penjadwalan',
    sekolah: 'Profil Sekolah',
    guru: 'Guru',
    kelas: 'Kelas',
    mapel: 'Mata Pelajaran',
    login: 'Masuk',
    logout: 'Keluar',
    register: 'Daftar Akun Baru',
    backToHome: 'Kembali ke Beranda',
    makeSchedule: 'Buat Jadwal',
    makeScheduleNow: 'Buat Jadwal Sekarang',
    enterDashboard: 'Masuk Dashboard',
    welcome: 'Selamat datang di Jadwale',
    loginSubtitle: 'Masuk untuk mengelola jadwal pelajaran sekolah Anda.',
    registerSubtitle: 'Mulai kelola jadwal sekolah Anda dengan efisien.',
    email: 'Email',
    password: 'Password',
    schoolName: 'Nama Sekolah',
    adminName: 'Nama Penanggung Jawab / Admin',
    npsnOptional: 'NPSN (Opsional)',
    noAccount: 'Belum memiliki akun?',
    hasAccount: 'Sudah memiliki akun?',
    registerNow: 'Daftar Sekarang',
    loginNow: 'Masuk Sekarang',
    showPassword: 'Tampilkan Password',
    hidePassword: 'Sembunyikan Password',
    features: 'Fitur Utama',
    versionUpdate: 'Sistem Penjadwalan Otomatis Sekolah Dasar (CSP AI)',
    superadminOnlyInfo: 'Informasi Status Sistem (Hanya Superadmin)',
    menuUtama: 'Menu Utama',
    masterData: 'Master Data',
    themeLight: 'Mode Terang',
    themeDark: 'Mode Gelap',
    language: 'Bahasa',
    guestMode: 'Pengunjung',

    // Login Draft Keys
    draftFound: 'Draf Jadwal Ditemukan',
    draftDesc: 'Anda memiliki draf pembuatan jadwal yang belum selesai.',
    continueDraft: 'Lanjutkan Draf',
    discardDraft: 'Abaikan Draf',
    
    // Share Page Keys
    publicScheduleTitle: 'Jadwal Pelajaran Sekolah',
    publicLinkBadge: 'Link Bagikan Publik (Read Only)',
    selectClass: 'Pilih Rombel / Kelas',
    selectClassPrompt: 'Silakan pilih kelas di sebelah kiri untuk melihat jadwal pelajaran',
    periodHeader: 'JP',
    timeHeader: 'Waktu',
    ceremony: 'Upacara',
    emptySlot: 'Kosong',

    // Landing Hero & Features
    heroTitle: 'Buat jadwal sekolah dasar tanpa ribet, tanpa bentrok.',
    heroSubtitle: 'Cukup isi data guru, mata pelajaran, dan kelas — sistem yang buatkan jadwalnya. Dirancang khusus untuk memudahkan operator sekolah dan guru SD di seluruh Indonesia.',
    feature1Title: 'Jadwal Otomatis',
    feature1Desc: 'Isi data guru dan mapel, lalu biarkan sistem menyusun jadwal dalam hitungan detik tanpa bentrok.',
    feature2Title: 'Manajemen Mapel',
    feature2Desc: 'Kelola alokasi jam mengajar per mata pelajaran sesuai dengan kebutuhan kurikulum sekolah dasar.',
    feature3Title: 'Ketersediaan Guru',
    feature3Desc: 'Atur hari libur guru honorer atau guru bidang agar jadwal menyesuaikan kehadiran mereka secara otomatis.',

    // Dashboard Greetings & Stats
    goodMorning: 'Selamat Pagi',
    goodAfternoon: 'Selamat Siang',
    goodEvening: 'Selamat Sore',
    goodNight: 'Selamat Malam',
    welcomeDashboard: 'Selamat datang di dashboard Jadwale. Mulai kelola jadwal pelajaran sekolah Anda.',
    scheduleActive: 'Jadwal Aktif',
    noSchedule: 'Belum Ada Jadwal',
    manage: 'Kelola',
    overviewTitle: 'Ringkasan Sekolah',
    totalGuru: 'Guru',
    descGuru: 'Tenaga pengajar terdaftar',
    totalKelas: 'Kelas',
    descKelas: 'Kelas aktif',
    totalMapel: 'Mata Pelajaran',
    descMapel: 'Mapel tersedia',
    totalJadwal: 'Jadwal Dibuat',
    descJadwal: 'Slot jadwal aktif',
    
    // Quick Actions & Export
    quickActions: 'Aksi Cepat',
    actionGenerateTitle: 'Generate Jadwal',
    actionGenerateDesc: 'Buat jadwal otomatis menggunakan algoritma CSP',
    actionGuruTitle: 'Kelola Guru',
    actionGuruDesc: 'Tambah, edit, atau atur ketersediaan guru',
    actionKelasTitle: 'Kelola Kelas',
    actionKelasDesc: 'Atur kelas, tingkatan, dan wali kelas',
    actionMapelTitle: 'Mata Pelajaran',
    actionMapelDesc: 'Konfigurasi mapel dan alokasi JP per minggu',

    exportShare: 'Ekspor & Bagikan',
    downloadPdf: 'Unduh PDF',
    pdfReady: 'Siap cetak',
    downloadExcel: 'Unduh Excel',
    excelFormat: 'Format .xlsx',
    createShareLink: 'Buat Link Bagikan',
    copiedLink: 'Disalin!',

    // Sidebar Groups & Mobile Navigation
    superadminGroup: 'Panel Superadmin',
    teacherAreaGroup: 'Area Tenaga Pendidik',
    publicAreaGroup: 'Area Pengguna Umum',
    designerGroup: 'Studio Designer',
    summaryVerification: 'Ringkasan & Sekolah',
    allUsersMenu: 'Semua Pengguna',
    myTeachingSchedule: 'Jadwal Mengajar Saya',
    viewSchoolSchedule: 'Lihat Jadwal Sekolah',
    templateManagement: 'Manajemen Template',
    myAccountMobile: 'Akun Saya',
    mobileMenuTitle: 'Menu Pengguna & Pengaturan',
    confirmLogoutTitle: 'Keluar Akun?',
    confirmLogoutDesc: 'Apakah Anda yakin ingin keluar dari sesi aplikasi saat ini?',
    schoolHierarchyTitle: 'Daftar Sekolah & Akun Terikat',
    schoolHierarchyDesc: 'Klik pada sekolah untuk melihat rincian akun Admin Sekolah dan Tenaga Pendidik (Guru) terdaftar.',
    linkedTeachersCount: 'Tenaga Pendidik Terdaftar',

    // Schedule Tabs
    autoGeneratorTab: 'Generator Otomatis',
    viewScheduleTab: 'Lihat Jadwal',

    // Sekolah Page Keys
    sekolahConfigTitle: 'Pengaturan Profil Sekolah',
    sekolahConfigSubtitle: 'Atur identitas sekolah, waktu jam pelajaran, dan jadwal istirahat',
    saving: 'Menyimpan...',
    saveChanges: 'Simpan Perubahan',
    schoolIdentity: 'Identitas Sekolah',
    schoolType: 'Tipe Sekolah',
    nonParallelOption: 'Biasa (1 kelas/tingkat)',
    parallelOption: 'Paralel (Multi kelas)',
    address: 'Alamat',
    periodsSchoolDays: 'Jam Pelajaran & Hari Sekolah',
    startTime: 'Jam Mulai',
    jpDuration: 'Durasi 1 JP (menit)',
    schoolDays: 'Jumlah Hari Sekolah',
    days5: '5 Hari (Senin - Jumat)',
    days6: '6 Hari (Senin - Sabtu)',
    routineBreak: 'Kegiatan Pembiasaan & Istirahat',
    morningRoutine: 'Pembiasaan Pagi',
    morningRoutineDesc: 'Asmaul Husna, Senam, Literasi dll. Jika hari Senin ada upacara, pembiasaan dilaksanakan setelah upacara.',
    routineDuration: 'Durasi Pembiasaan (menit)',
    mondayCeremony: 'Upacara Senin',
    mondayCeremonyDesc: 'Kunci JP 1 Hari Senin',
    break1: 'Istirahat 1',
    break2: 'Istirahat 2',
    durationMin: 'Durasi (menit)',
    afterJp: 'Setelah JP Ke-',
    simulatedSchedule: 'Simulasi Jam Pelajaran Harian',

    // Step 2 Waktu Keys
    breakScheduleTitle: 'Pengaturan Jam Istirahat',
    addBtn: 'Tambah',
    noBreakSet: 'Belum ada waktu istirahat yang diatur',
    afterJpNum: 'Setelah JP ke-',
    dailyJpLoadTitle: 'Beban JP Per Hari',
    dailyJpLoadDesc: 'Tentukan jumlah jam pelajaran (JP) per hari untuk setiap kelas.',

    // Step 3 Master Keys
    addTimeBtn: 'Tambah Jam Ketersediaan',

    // Wizard Steps
    wizardTitle: 'Wizard Jadwal',
    step1Short: 'Konfigurasi',
    step2Short: 'Waktu',
    step3Short: 'Master',
    step4Short: 'Relasi',
    step5Short: 'Generate',

    step1Title: 'Langkah 1: Konfigurasi Sekolah',
    step1Desc: 'Atur struktur kelas di sekolah Anda. Perubahan akan disimpan secara otomatis.',
    parallelSystem: 'Sistem Paralel',
    parallelDesc: 'Apakah ada lebih dari satu kelas per tingkatan?',
    classNaming: 'Penamaan Kelas Paralel',
    alphabet: 'Alfabet',
    alphabetExample: 'Contoh: 1A, 1B, 1C',
    numberLabel: 'Angka',
    numberExample: 'Contoh: 1-1, 1-2, 1-3',
    tingkatanCount: 'Jumlah Tingkatan',
    gradeSuffix: 'Tingkat (SD = 6)',
    avgClassesPerGrade: 'Rata-rata Kelas / Tingkatan',
    previewFormat: 'Pratinjau Format Kelas',

    step2Title: 'Langkah 2: Pengaturan Waktu',
    step2Desc: 'Atur hari sekolah, durasi Jam Pelajaran (JP), dan waktu istirahat.',
    schoolDaysCount: 'Jumlah Hari Sekolah',
    days5Short: '5 Hari (Sen-Jum)',
    days6Short: '6 Hari (Sen-Sab)',
    startTimeLabel: 'Jam Mulai',
    durationJpLabel: 'Durasi 1 JP',
    minutesSuffix: 'Menit',
    flagCeremony: 'Upacara Bendera',
    flagCeremonyDesc: 'Blokir JP pertama di hari Senin',
    routineActivity: 'Kegiatan Pembiasaan',
    routineActivityDesc: '(Asmaul Husna, Literasi, Senam, dll. Jika hari Senin ada upacara, pembiasaan dilaksanakan setelah upacara)',
    routineDurationLabel: 'Durasi Pembiasaan:',

    breakLabel: 'Istirahat',
    afterJpLabel: 'Setelah JP ke-',
    durationMinutesLabel: 'Durasi (Menit)',
    removeBreak: 'Hapus Istirahat',
    addBreak: 'Tambah Istirahat',

    teacherFullName: 'Nama Lengkap Guru',
    nipOptional: 'NIP (Opsional)',

    step3Title: 'Langkah 3: Master Data Guru & Mapel',
    step3Desc: 'Kelola daftar mata pelajaran dan guru pengajar.',
    subjectsTab: 'Mata Pelajaran',
    teachersTab: 'Data Guru',
    addSubjectBtn: 'Tambah Mapel',
    priorityMorningMapel: 'Mapel Prioritas Pagi',
    weeklyJpLoad: 'Alokasi Jam Pelajaran (JP) Per Minggu',
    addTeacherBtn: 'Tambah Guru',
    availabilityLabel: 'Ketersediaan Mengajar Guru',

    step4Title: 'Langkah 4: Pengaturan Relasi Guru & Mapel',
    step4Desc: 'Tentukan wali kelas dan pengampu mata pelajaran untuk setiap kelas.',
    needStep3Notice: 'Silakan isi data Mata Pelajaran dan Guru terlebih dahulu di Langkah 3.',
    homeroomTab: 'Wali Kelas',
    subjectTeacherTab: 'Pengampu Mapel',
    homeroomNotice: 'Pilih satu guru sebagai wali kelas untuk setiap rombel.',
    selectHomeroomPlaceholder: '-- Pilih Wali Kelas --',
    defaultSubjectsTitle: 'Mata Pelajaran Wajib Kelas',
    subjectTeacherNotice: 'Tentukan guru yang mengajar mata pelajaran untuk setiap tingkatan kelas.',
    addTeacherForSubject: 'Tambah Guru Pengampu',
    noTeacherForSubject: 'Belum ada guru pengampu yang diatur',
    selectTeacherPlaceholder: '-- Pilih Guru --',
    taughtClassesLabel: 'Kelas Yang Diajar',
    gradeShort: 'Tingkat',
    newSubjectDefault: 'Mata Pelajaran Baru',
    newTeacherDefault: 'Guru Baru',

    monday: 'Senin',
    tuesday: 'Selasa',
    wednesday: 'Rabu',
    thursday: 'Kamis',
    friday: 'Jumat',
    saturday: 'Sabtu',

    step5Title: 'Generate Jadwal Pelajaran',
    step5Desc: 'Sistem AI akan menyusun jadwal otomatis tanpa bentrok.',
    restrictedAccessTitle: 'Akses Terbatas',
    restrictedAccessDesc: 'Silakan login untuk menyimpan dan melihat hasil jadwal secara permanen.',
    loginNowBtn: 'Login Sekarang',
    savingData: 'Menyimpan Data...',
    startGenerateBtn: 'Mulai Generate',

    cancel: 'Batal',
    save: 'Simpan',
    back: 'Kembali',
    next: 'Lanjut',
    finish: 'Selesai',
    backBtn: 'Kembali',
    nextBtn: 'Lanjut',
    finishBtn: 'Selesai',
    pendingTeacherNotice: 'Pendaftaran Akun Guru Menunggu Verifikasi',
    verifyTeacherBtn: 'Verifikasi',
    superadminPanel: 'Panel Superadmin',
    superadminDesc: 'Pengelolaan sistem, verifikasi sekolah, dan manajemen akun secara menyeluruh.',
    createDesigner: 'Buat Akun Designer',
    tabAllUsers: 'Semua Akun Sistem',
    registeredSchools: 'Sekolah Terdaftar',
    pendingVerification: 'Menunggu Verifikasi',
    tabDesigner: 'Akun Designer',
    createDesignerTitle: 'Buat Akun Template Designer',
    designerName: 'Nama Designer',
    designerEmail: 'Email Designer',
    initialPassword: 'Password Awal',
    tabAdminSekolah: 'Admin Sekolah',
    totalTeachersCount: 'Jumlah Guru',
    totalClassesCount: 'Jumlah Kelas',
    totalSubjectsCount: 'Jumlah Mapel',
    approveVerify: 'Setujui & Verifikasi',
    manageAccounts: 'Pengelolaan Seluruh Akun & Sekolah',
    tabTenagaPendidik: 'Tenaga Pendidik',
    tabUserBiasa: 'User Biasa',
    tabSekolahProfile: 'Profil Sekolah',
    accountActive: 'Aktif',
    accountInactive: 'Nonaktif',
    usernameEmail: 'Username / Email',
    accountStatus: 'Status Akun',
    deactivateBtn: 'Nonaktifkan',
    activateBtn: 'Aktifkan',
  },
  en: {
    appName: 'Jadwale',
    appSubtitle: 'Automatic Scheduling',
    home: 'Home',
    dashboard: 'Dashboard',
    jadwal: 'Scheduling',
    sekolah: 'School Profile',
    guru: 'Teachers',
    kelas: 'Classes',
    mapel: 'Subjects',
    login: 'Login',
    logout: 'Logout',
    register: 'Create New Account',
    backToHome: 'Back to Home',
    makeSchedule: 'Create Schedule',
    makeScheduleNow: 'Create Schedule Now',
    enterDashboard: 'Enter Dashboard',
    welcome: 'Welcome to Jadwale',
    loginSubtitle: 'Sign in to manage your school timetable.',
    registerSubtitle: 'Start managing your school timetable efficiently.',
    email: 'Email',
    password: 'Password',
    schoolName: 'School Name',
    adminName: 'Admin / Person in Charge Name',
    npsnOptional: 'NPSN (Optional)',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    registerNow: 'Register Now',
    loginNow: 'Login Now',
    showPassword: 'Show Password',
    hidePassword: 'Hide Password',
    features: 'Key Features',
    versionUpdate: 'Automatic Primary School Scheduling System (AI CSP)',
    superadminOnlyInfo: 'System Status Info (Superadmin Only)',
    menuUtama: 'Main Menu',
    masterData: 'Master Data',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    language: 'Language',
    guestMode: 'Guest',

    // Login Draft Keys
    draftFound: 'Schedule Draft Found',
    draftDesc: 'You have an unfinished schedule creation draft.',
    continueDraft: 'Continue Draft',
    discardDraft: 'Discard Draft',

    // Share Page Keys
    publicScheduleTitle: 'School Timetable',
    publicLinkBadge: 'Public Share Link (Read Only)',
    selectClass: 'Select Class',
    selectClassPrompt: 'Please select a class on the left to view timetable',
    periodHeader: 'Period',
    timeHeader: 'Time',
    ceremony: 'Flag Ceremony',
    emptySlot: 'Empty',

    // Landing Hero & Features
    heroTitle: 'Create primary school timetables effortlessly without conflicts.',
    heroSubtitle: 'Simply fill in teachers, subjects, and classes — our AI engine builds your timetable in seconds.',
    feature1Title: 'Automated Timetable',
    feature1Desc: 'Input data and let the system solve schedule conflicts automatically.',
    feature2Title: 'Subject Management',
    feature2Desc: 'Manage teach hours per subject according to primary school curriculum needs.',
    feature3Title: 'Teacher Availability',
    feature3Desc: 'Configure part-time teacher days off so schedule aligns with attendance.',

    // Dashboard Greetings & Stats
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    goodNight: 'Good Night',
    welcomeDashboard: 'Welcome to Jadwale dashboard. Manage your school schedule effectively.',
    scheduleActive: 'Active Schedule',
    noSchedule: 'No Schedule Yet',
    manage: 'Manage',
    overviewTitle: 'School Overview',
    totalGuru: 'Teachers',
    descGuru: 'Registered teaching staff',
    totalKelas: 'Classes',
    descKelas: 'Active classes',
    totalMapel: 'Subjects',
    descMapel: 'Available subjects',
    totalJadwal: 'Schedules Created',
    descJadwal: 'Active schedule slots',

    // Quick Actions & Export
    quickActions: 'Quick Actions',
    actionGenerateTitle: 'Generate Timetable',
    actionGenerateDesc: 'Build automatic schedule using CSP algorithm',
    actionGuruTitle: 'Manage Teachers',
    actionGuruDesc: 'Add, edit, or configure teacher availability',
    actionKelasTitle: 'Manage Classes',
    actionKelasDesc: 'Configure classes, grades, and homeroom teachers',
    actionMapelTitle: 'Subjects',
    actionMapelDesc: 'Configure subjects and weekly periods',

    exportShare: 'Export & Share',
    downloadPdf: 'Download PDF',
    pdfReady: 'Print ready',
    downloadExcel: 'Download Excel',
    excelFormat: '.xlsx format',
    createShareLink: 'Create Shareable Link',
    copiedLink: 'Copied!',

    // Sidebar Groups & Mobile Navigation
    superadminGroup: 'Superadmin Panel',
    teacherAreaGroup: 'Teacher Area',
    publicAreaGroup: 'Public User Area',
    designerGroup: 'Designer Studio',
    summaryVerification: 'Overview & Schools',
    allUsersMenu: 'All System Users',
    myTeachingSchedule: 'My Teaching Schedule',
    viewSchoolSchedule: 'View School Schedule',
    templateManagement: 'Template Management',
    myAccountMobile: 'My Account',
    mobileMenuTitle: 'User Profile & Settings',
    confirmLogoutTitle: 'Log Out of Account?',
    confirmLogoutDesc: 'Are you sure you want to log out of your current session?',
    schoolHierarchyTitle: 'School Directory & Linked Accounts',
    schoolHierarchyDesc: 'Select a school to view detailed linked School Admin and Teacher accounts.',
    linkedTeachersCount: 'Registered Teaching Staff',

    // Schedule Tabs
    autoGeneratorTab: 'Auto Generator',
    viewScheduleTab: 'View Schedule',

    // Sekolah Page Keys
    sekolahConfigTitle: 'School Profile Settings',
    sekolahConfigSubtitle: 'Configure school identity, class periods, and breaks',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    schoolIdentity: 'School Identity',
    schoolType: 'School Type',
    nonParallelOption: 'Single (1 class/grade)',
    parallelOption: 'Parallel (Multi class)',
    address: 'Address',
    periodsSchoolDays: 'Periods & School Days',
    startTime: 'Start Time',
    jpDuration: '1 Period Duration (mins)',
    schoolDays: 'School Days',
    days5: '5 Days (Monday - Friday)',
    days6: '6 Days (Monday - Saturday)',
    routineBreak: 'Routine & Break Settings',
    morningRoutine: 'Morning Routine',
    morningRoutineDesc: 'Literacy, Exercise, Assemblies. If Monday has ceremony, routine is held after ceremony.',
    routineDuration: 'Routine Duration (mins)',
    mondayCeremony: 'Monday Ceremony',
    mondayCeremonyDesc: 'Block 1st Period on Mondays',
    break1: 'Break 1',
    break2: 'Break 2',
    durationMin: 'Duration (mins)',
    afterJp: 'After Period #',
    simulatedSchedule: 'Daily Period Simulation',

    // Step 2 Waktu Keys
    breakScheduleTitle: 'Break Schedule Settings',
    addBtn: 'Add',
    noBreakSet: 'No break time set',
    afterJpNum: 'After Period #',
    dailyJpLoadTitle: 'Daily Period Load',
    dailyJpLoadDesc: 'Set number of periods per day for each class.',

    // Step 3 Master Keys
    addTimeBtn: 'Add Available Hours',

    // Wizard Steps
    wizardTitle: 'Schedule Wizard',
    step1Short: 'Configuration',
    step2Short: 'Time Settings',
    step3Short: 'Master Data',
    step4Short: 'Relations',
    step5Short: 'Generate',

    step1Title: 'Step 1: School Configuration',
    step1Desc: 'Set up class structures in your school. Changes are saved automatically.',
    parallelSystem: 'Parallel System',
    parallelDesc: 'Is there more than one class per grade level?',
    classNaming: 'Parallel Class Naming',
    alphabet: 'Alphabet',
    alphabetExample: 'Example: 1A, 1B, 1C',
    numberLabel: 'Number',
    numberExample: 'Example: 1-1, 1-2, 1-3',
    tingkatanCount: 'Number of Grade Levels',
    gradeSuffix: 'Grades (Elementary = 6)',
    avgClassesPerGrade: 'Average Classes / Grade',
    previewFormat: 'Class Format Preview',

    step2Title: 'Step 2: Time Settings',
    step2Desc: 'Set school days, period duration, and break times.',
    schoolDaysCount: 'School Days Count',
    days5Short: '5 Days (Mon-Fri)',
    days6Short: '6 Days (Mon-Sat)',
    startTimeLabel: 'Start Time',
    durationJpLabel: '1 Period Duration',
    minutesSuffix: 'Minutes',
    flagCeremony: 'Flag Ceremony',
    flagCeremonyDesc: 'Block 1st period on Mondays',
    routineActivity: 'Habituation Activity',
    routineActivityDesc: '(Literacy, Exercise, Morning Assembly. If Monday has ceremony, routine is held after ceremony)',
    routineDurationLabel: 'Activity Duration:',

    breakLabel: 'Break Time',
    afterJpLabel: 'After Period #',
    durationMinutesLabel: 'Duration (Minutes)',
    removeBreak: 'Remove Break',
    addBreak: 'Add Break',

    teacherFullName: 'Teacher Full Name',
    nipOptional: 'NIP (Optional)',

    step3Title: 'Step 3: Teacher & Subject Master Data',
    step3Desc: 'Manage subjects and teachers list.',
    subjectsTab: 'Subjects',
    teachersTab: 'Teachers List',
    addSubjectBtn: 'Add Subject',
    priorityMorningMapel: 'Morning Priority Subject',
    weeklyJpLoad: 'Weekly Period Allocation',
    addTeacherBtn: 'Add Teacher',
    availabilityLabel: 'Teacher Availability',

    step4Title: 'Step 4: Teacher & Subject Relations',
    step4Desc: 'Assign homeroom teachers and subject teachers for each class.',
    needStep3Notice: 'Please fill Subject and Teacher data first in Step 3.',
    homeroomTab: 'Homeroom Teachers',
    subjectTeacherTab: 'Subject Teachers',
    homeroomNotice: 'Select one homeroom teacher for each class.',
    selectHomeroomPlaceholder: '-- Select Homeroom Teacher --',
    defaultSubjectsTitle: 'Default Class Subjects',
    subjectTeacherNotice: 'Assign teachers for subjects across grade levels.',
    addTeacherForSubject: 'Add Teaching Teacher',
    noTeacherForSubject: 'No teaching teacher configured yet',
    selectTeacherPlaceholder: '-- Select Teacher --',
    taughtClassesLabel: 'Taught Classes',
    gradeShort: 'Grade',
    newSubjectDefault: 'New Subject',
    newTeacherDefault: 'New Teacher',

    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',

    step5Title: 'Generate Timetable',
    step5Desc: 'AI system will compose conflict-free schedule automatically.',
    restrictedAccessTitle: 'Restricted Access',
    restrictedAccessDesc: 'Please login to save and view schedule results permanently.',
    loginNowBtn: 'Login Now',
    savingData: 'Saving Data...',
    startGenerateBtn: 'Start Generate',

    cancel: 'Cancel',
    save: 'Save',
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
    backBtn: 'Back',
    nextBtn: 'Next',
    finishBtn: 'Finish',
    pendingTeacherNotice: 'Teacher Account Registrations Pending Verification',
    verifyTeacherBtn: 'Verify',
    superadminPanel: 'Superadmin Panel',
    superadminDesc: 'Overall system administration, school verification, and account management.',
    createDesigner: 'Create Designer Account',
    tabAllUsers: 'All System Accounts',
    registeredSchools: 'Registered Schools',
    pendingVerification: 'Pending Verification',
    tabDesigner: 'Designer Accounts',
    createDesignerTitle: 'Create Template Designer Account',
    designerName: 'Designer Name',
    designerEmail: 'Designer Email',
    initialPassword: 'Initial Password',
    tabAdminSekolah: 'School Admins',
    totalTeachersCount: 'Total Teachers',
    totalClassesCount: 'Total Classes',
    totalSubjectsCount: 'Total Subjects',
    approveVerify: 'Approve & Verify',
    manageAccounts: 'Manage Accounts & School Profiles',
    tabTenagaPendidik: 'Teaching Staff',
    tabUserBiasa: 'Standard Users',
    tabSekolahProfile: 'School Profiles',
    accountActive: 'Active',
    accountInactive: 'Inactive',
    usernameEmail: 'Username / Email',
    accountStatus: 'Account Status',
    deactivateBtn: 'Deactivate',
    activateBtn: 'Activate',
  },
};
